In [3]:
## Lets see what we have for UQ analysis in the data
# imports 
import os
import pickle

In [1]:
root = '/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/runs_slake/llava_med_slake'
explanations_folder = 'explanations'
grounding_bioclip_folder = 'grounding'
grounding_llama32_folder = 'grounding_with_llama32'
grounding_llama32_90b_folder = 'grounding_with_llama32_90b'
grounding_qwen_vl_folder = 'grounding_with_qwen_vl'

In [14]:
# lets see what we have in the explanations folder
explanations_path = os.path.join(root, explanations_folder)
explanations_files = os.listdir(explanations_path) # can we sort them by the question id ? Answer is yes How ?
explanations_files.sort()

# load the first explanation file
explanation_file = explanations_files[0]
print('Explanation File:', explanation_file)
explanation_file_path = os.path.join(explanations_path, explanation_file)
with open(explanation_file_path, 'rb') as f:
    explanation = pickle.load(f)

explanation.keys()

# dict_keys(['img_names', 'locations', 'answers', 'modalities', 'base_types', 'answer_types', 'questions', 'qids', 'content_types', 'triples', 'img_ids', 'q_langs', 'promptified_questions', 'image_paths', 'response_0', 'response_1', 'response_2', 'response_3', 'response_4', 'response_5', 'response_6', 'response_7', 'response_8', 'response_9', 'response_10', 'response_11', 'response_12', 'response_13', 'response_14', 'response_15', 'response_16', 'response_17', 'response_18', 'response_19'])
# question
question = explanation['questions'][0]
print('Question:', question)
gt_answer = explanation['answers'][0]
print('GT Answer:', gt_answer)
# what values we have for each response ?
# print(explanation['response_0'].keys())
# dict_keys(['prompt', 'generated_token_ids', 'decoded_outputs', 'transition_scores'])
print('Response 0:', explanation['response_0']['decoded_outputs'])
# print all the responses
for i in range(20):
    print('Response', i, ':', explanation['response_'+str(i)]['decoded_outputs'])

Explanation File: explanations_0.pkl
Question: What modality is used to take this image?
GT Answer: MRI
Response 0: The image is a T1-weighted MRI, which is a type of magnetic resonance imaging that uses a specific pulse sequence to generate images with different contrasts. In this case, the image is focused on the abdomen, and the main organ visible is the lung and spinal cord.
Response 0 : The image is a T1-weighted MRI, which is a type of magnetic resonance imaging that uses a specific pulse sequence to generate images with different contrasts. In this case, the image is focused on the abdomen, and the main organ visible is the lung and spinal cord.
Response 1 : The image is an MRI scan of the abdomen, which shows a large mass in the left kidney. The mass is well-defined and has a complex internal structure. It is important to note that further evaluation and tests would be needed to determine the exact nature and cause of the mass.
Response 2 : The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main organ in the image is the lung, which is part of the respiratory system. The spinal cord is also visible in the image, as it is located within the vertebral column in the abdominal region.
Response 3 : The image is a T2-weighted MRI of the abdomen, focusing on the lung and spinal cord.
Response 4 : The image is an MRI of the abdomen, showing the lung and spinal cord. The lung is a part of the respiratory system, while the spinal cord is a bundle of nerve fibers that connects the brain to the rest of the body.
Response 5 : The image is a post-contrast MRI of the abdomen, which shows a mass in the left breast. The mass has a heterogeneous enhancement pattern, which means that the contrast agent used during the MRI highlights the mass in an irregular or uneven manner. This can be indicative of various types of lesions, such as cysts, fibroadenomas, or malignancies. Further evaluation and tests would be needed to determine the exact nature and cause of the mass.
Response 6 : The MRI image shows a large, well-defined, and heterogeneous mass in the abdomen. This mass is displacing the Lung and Spinal Cord. The exact nature of the mass would require further analysis and clinical correlation to determine its cause and significance.
Response 7 : The image is a T1-weighted MRI of the abdomen, focusing on the lung and spinal cord.
Response 8 : The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main organs in the image are the lung and spinal cord, as they are the primary structures being examined.
Response 9 : The image is a T2-weighted MRI of the abdomen, which shows a lobulated mass with internal septations in the left lung and spinal cord. This mass is associated with the patient's diagnosis of epithelioid hemangioendothelioma (EHE).
Response 10 : The image is a T1-weighted MRI of the abdomen. T1-weighted images are a type of MRI sequence that provides good anatomical detail and is often used to visualize the structure of organs and tissues. In this case, the image shows the Lung and Spinal Cord, which are two important organs in the abdomen.
Response 11 : The main organ in the image is the Lung and Spinal Cord.
Response 12 : The image is a T2-weighted MRI of the abdomen. It is a sagittal view, which means it is a side view of the body, showing the left and right sides of the abdomen. The main organ in the image is the Lung and Spinal Cord.
Response 13 : The image is a cardiac MRI, which is a magnetic resonance imaging scan focused on the heart. Cardiac MRI is a non-invasive imaging technique that provides detailed information about the structure and function of the heart, including the chambers, valves, and surrounding blood vessels. It can help diagnose various heart conditions and guide treatment decisions.
Response 14 : The main organ in the image is the lung.
Response 15 : The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main findings in the image are the presence of a large left pleural effusion and a large intraperitoneal mass, which is causing a mass effect on the spinal cord.
Response 16 : The image is a T2-weighted MRI of the abdomen, which is a specific type of magnetic resonance imaging that provides detailed information about the tissues and organs within the abdominal cavity. In this case, the main organ in the image is the Lung and Spinal Cord.
Response 17 : The image is a T2-weighted MRI of the abdomen, which includes the Lung and Spinal Cord.
Response 18 : The image is a T2-weighted MRI of the abdomen, which includes the lung and spinal cord. T2-weighted images are a specific type of MRI sequence that provides detailed information about the tissue composition and can help visualize certain abnormalities or pathologies.
Response 19 : The image is an MRI of the abdomen, and it shows a mass in the right lung and spinal cord. The mass is likely a metastasis, which is a secondary cancerous growth that has spread from another part of the body. In this case, the mass is located in the right lung and spinal cord.

In [18]:
# lets see what we have in the grounding folder for the responses
grounding_path = os.path.join(root, grounding_bioclip_folder)
grounding_files = os.listdir(grounding_path)
grounding_files.sort()

# load the first grounding file
grounding_file = grounding_files[0]
print('Grounding File:', grounding_file)
grounding_file_path = os.path.join(grounding_path, grounding_file)
with open(grounding_file_path, 'rb') as f:
    grounding = pickle.load(f)
    
# dict_keys(['question_id', 'response_0', 'response_1', 'response_2', 'response_3', 'response_4', 'response_5', 'response_6', 'response_7', 'response_8', 'response_9', 'response_10', 'response_11', 'response_12', 'response_13', 'response_14', 'response_15', 'response_16', 'response_17', 'response_18', 'response_19'])
# grounding['response_0'].keys()
# dict_keys(['decoded_outputs', 'biomedclip_score'])

# Lets visualize the biomedclip grounding for all the responses
for i in range(20):
    # print('Response', i, ':', grounding['response_'+str(i)]['decoded_outputs'])
    print('Response', i, 'Biomedclip Score:', grounding['response_'+str(i)]['biomedclip_score'])

Grounding File: clipscore_0.pkl
Response 0 Biomedclip Score: 35.556427001953125
Response 1 Biomedclip Score: 32.47749328613281
Response 2 Biomedclip Score: 34.951759338378906
Response 3 Biomedclip Score: 36.03338623046875
Response 4 Biomedclip Score: 32.95039367675781
Response 5 Biomedclip Score: 40.9133186340332
Response 6 Biomedclip Score: 34.564815521240234
Response 7 Biomedclip Score: 36.46287536621094
Response 8 Biomedclip Score: 33.86470413208008
Response 9 Biomedclip Score: 38.02631759643555
Response 10 Biomedclip Score: 35.28411865234375
Response 11 Biomedclip Score: 25.5179443359375
Response 12 Biomedclip Score: 32.49067687988281
Response 13 Biomedclip Score: 29.92745018005371
Response 14 Biomedclip Score: 26.25503158569336
Response 15 Biomedclip Score: 37.207603454589844
Response 16 Biomedclip Score: 35.7288818359375
Response 17 Biomedclip Score: 36.034942626953125
Response 18 Biomedclip Score: 34.909114837646484
Response 19 Biomedclip Score: 35.194007873535156

In [22]:
# Now lets see what we have in the grounding folder of llama32 11b
grounding_path = os.path.join(root, grounding_llama32_folder)
grounding_files = os.listdir(grounding_path)
grounding_files.sort()

# load the first grounding file
grounding_file = grounding_files[0]
print('Grounding File:', grounding_file)
grounding_file_path = os.path.join(grounding_path, grounding_file)
with open(grounding_file_path, 'rb') as f:
    grounding = pickle.load(f)
    
grounding.keys()
# dict_keys(['img_names', 'locations', 'answers', 'modalities', 'base_types', 'answer_types', 'questions', 'qids', 'content_types', 'triples', 'img_ids', 'q_langs', 'promptified_questions', 'image_paths', 'response_0', 'response_1', 'response_2', 'response_3', 'response_4', 'response_5', 'response_6', 'response_7', 'response_8', 'response_9', 'response_10', 'response_11', 'response_12', 'response_13', 'response_14', 'response_15', 'response_16', 'response_17', 'response_18', 'response_19'])
# grounding['response_0'].keys()
# dict_keys(['prompt', 'generated_token_ids', 'decoded_outputs', 'transition_scores', 'llama_32_response'])
# get the llama32 response for all the responses
for i in range(20):
    print('Response', i, 'Llama32 Response:', grounding['response_'+str(i)]['llama_32_response'])

Grounding File: grounding_0.pkl
Response 0 Llama32 Response: No.<|eot_id|>
Response 1 Llama32 Response: No.<|eot_id|>
Response 2 Llama32 Response: No.<|eot_id|>
Response 3 Llama32 Response: No.<|eot_id|>
Response 4 Llama32 Response: No.<|eot_id|>
Response 5 Llama32 Response: No.<|eot_id|>
Response 6 Llama32 Response: No.<|eot_id|>
Response 7 Llama32 Response: No.<|eot_id|>
Response 8 Llama32 Response: No.<|eot_id|>
Response 9 Llama32 Response: No.<|eot_id|>
Response 10 Llama32 Response: No.<|eot_id|>
Response 11 Llama32 Response: No.<|eot_id|>
Response 12 Llama32 Response: No.<|eot_id|>
Response 13 Llama32 Response: No.<|eot_id|>
Response 14 Llama32 Response: No.<|eot_id|>
Response 15 Llama32 Response: No.<|eot_id|>
Response 16 Llama32 Response: No.<|eot_id|>
Response 17 Llama32 Response: No.<|eot_id|>
Response 18 Llama32 Response: No.<|eot_id|>
Response 19 Llama32 Response: No.<|eot_id|>

In [25]:
# Now lets see what we have in the grounding folder of llama32 90b
grounding_path = os.path.join(root, grounding_llama32_90b_folder)
grounding_files = os.listdir(grounding_path)
grounding_files.sort()

# load the first grounding file
grounding_file = grounding_files[0]
print('Grounding File:', grounding_file)
grounding_file_path = os.path.join(grounding_path, grounding_file)
with open(grounding_file_path, 'rb') as f:
    grounding = pickle.load(f)
    
grounding.keys()
# dict_keys(['img_names', 'locations', 'answers', 'modalities', 'base_types', 'answer_types', 'questions', 'qids', 'content_types', 'triples', 'img_ids', 'q_langs', 'promptified_questions', 'image_paths', 'response_0', 'response_1', 'response_2', 'response_3', 'response_4', 'response_5', 'response_6', 'response_7', 'response_8', 'response_9', 'response_10', 'response_11', 'response_12', 'response_13', 'response_14', 'response_15', 'response_16', 'response_17', 'response_18', 'response_19'])

grounding['response_0'].keys()
# dict_keys(['prompt', 'generated_token_ids', 'decoded_outputs', 'transition_scores', 'llama_32_response'])

# get the llama32 response for all the responses
for i in range(20):
    print('Response', i, 'Llama32 90b Response:', grounding['response_'+str(i)]['llama_32_response'])

Grounding File: grounding_0.pkl
Response 0 Llama32 90b Response: No.<|eot_id|>
Response 1 Llama32 90b Response: No.<|eot_id|>
Response 2 Llama32 90b Response: No.<|eot_id|>
Response 3 Llama32 90b Response: No.<|eot_id|>
Response 4 Llama32 90b Response: No.<|eot_id|>
Response 5 Llama32 90b Response: No.<|eot_id|>
Response 6 Llama32 90b Response: No.<|eot_id|>
Response 7 Llama32 90b Response: No.<|eot_id|>
Response 8 Llama32 90b Response: No.<|eot_id|>
Response 9 Llama32 90b Response: No.<|eot_id|>
Response 10 Llama32 90b Response: No.<|eot_id|>
Response 11 Llama32 90b Response: No.<|eot_id|>
Response 12 Llama32 90b Response: No.<|eot_id|>
Response 13 Llama32 90b Response: No.<|eot_id|>
Response 14 Llama32 90b Response: No.<|eot_id|>
Response 15 Llama32 90b Response: No.<|eot_id|>
Response 16 Llama32 90b Response: No.<|eot_id|>
Response 17 Llama32 90b Response: No.<|eot_id|>
Response 18 Llama32 90b Response: No.<|eot_id|>
Response 19 Llama32 90b Response: No.<|eot_id|>

In [29]:
# Now lets see what we have in the grounding folder of qwen_vl
grounding_path = os.path.join(root, grounding_qwen_vl_folder)
grounding_files = os.listdir(grounding_path)
grounding_files.sort()

# load the first grounding file
grounding_file = grounding_files[1]
print('Grounding File:', grounding_file)
grounding_file_path = os.path.join(grounding_path, grounding_file)
with open(grounding_file_path, 'rb') as f:
    grounding = pickle.load(f)
    
grounding.keys()
# dict_keys(['img_names', 'locations', 'answers', 'modalities', 'base_types', 'answer_types', 'questions', 'qids', 'content_types', 'triples', 'img_ids', 'q_langs', 'promptified_questions', 'image_paths', 'response_0', 'response_1', 'response_2', 'response_3', 'response_4', 'response_5', 'response_6', 'response_7', 'response_8', 'response_9', 'response_10', 'response_11', 'response_12', 'response_13', 'response_14', 'response_15', 'response_16', 'response_17', 'response_18', 'response_19'])

# dict_keys(['prompt', 'generated_token_ids', 'decoded_outputs', 'transition_scores', 'llama_32_response'])
for i in range(20):
    print('Response', i, 'Qwen_vl Response:', grounding['response_'+str(i)]['llama_32_response'])

Grounding File: grounding_10.pkl
Response 0 Qwen_vl Response: Yes<|im_end|>
Response 1 Qwen_vl Response: Yes<|im_end|>
Response 2 Qwen_vl Response: Yes
Explanation: The statement is correct. The image is indeed a CT scan of the abdomen, and the largest organ visible is the lung. The spinal cord is also present in the image, but it is not the largest organ. The lung is the most prominent organ in the scan, occupying a significant portion of the image.<|im_end|>
Response 3 Qwen_vl Response: Yes<|im_end|>
Response 4 Qwen_vl Response: Yes
Explanation: The statement "The largest organ in the picture is the lung" accurately reflects what is shown in the image. The lung is indeed the largest organ in the image, as it occupies a significant portion of the visual field. It is characterized by its distinctive shape and the presence of the bronchial tree, which is a network of
Response 5 Qwen_vl Response: Yes<|im_end|>
Response 6 Qwen_vl Response: Yes<|im_end|>
Response 7 Qwen_vl Response: Yes<|im_end|>
Response 8 Qwen_vl Response: Yes
Explanation: The statement "The image is an axial CT scan" accurately reflects what is shown in the image. An axial CT scan is a type of CT scan that is taken from the top of the body, which is consistent with the orientation of the image provided. The image is indeed an axial CT scan, as it displays a cross-sectional
Response 9 Qwen_vl Response: Yes<|im_end|>
Response 10 Qwen_vl Response: Yes<|im_end|>
Response 11 Qwen_vl Response: Yes<|im_end|>
Response 12 Qwen_vl Response: Yes
Explanation: The statement is correct. The image is indeed an axial contrast-enhanced CT scan of the abdomen. The largest organ visible in the image is the lung, which is located on the left side of the image (patient's right side) due to the perspective of the scan. The spinal cord is also visible, located centrally within the
Response 13 Qwen_vl Response: Yes
Explanation: The statement is correct. The image is indeed an axial view of a CT scan of the abdomen. The largest organ visible in the image is the lung, which is located on the left side of the image (patient's right side) due to the perspective of the scan. The spinal cord is also visible, running vertically through the
Response 14 Qwen_vl Response: Yes<|im_end|>
Response 15 Qwen_vl Response: Yes<|im_end|>
Response 16 Qwen_vl Response: Yes<|im_end|>
Response 17 Qwen_vl Response: Yes<|im_end|>
Response 18 Qwen_vl Response: Yes<|im_end|>
Response 19 Qwen_vl Response: Yes<|im_end|>

In [27]:
grounding['response_0'].keys()

dict_keys(['prompt', 'generated_token_ids', 'decoded_outputs', 'transition_scores', 'llama_32_response'])

In [19]:
# ok so now we have the results, 
import pandas as pd

acc_df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/accuracy.csv')
baseline_df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/baseline.csv')
grounding_df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/grounding.csv')
merged_df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged.csv')

In [20]:
acc_df.head()

   question_id  accuracy
0            0      0.85
1           10      0.05
2         1000      0.10
3         1001      0.00
4         1002      0.25

In [21]:
baseline_df.head()

,question_id,predictive_entropy,lexical_similarity,semantic_entropy,num_clusters,responses,resp_log_probs,question
0,0,1.244401,0.371253,1.055891,14,"['The image is a T1-weighted MRI, which is a t...","[-18.569684982299805, -33.829524993896484, -7....",What modality is used to take this image?
1,10,1.051882,0.359208,0.967955,15,['The image is a coronal view of an abdomen MR...,"[-22.405088424682617, -22.054996490478516, -6....",What is the largest organ in the picture?
2,1000,0.881631,0.364706,0.684908,16,['The black hole in the upper right corner of ...,"[-4.018756866455078, -14.954319953918457, -24....",What organ is the black hole in the upper righ...
3,1001,1.194139,0.360086,1.011172,18,"['The image is an abdominal MRI, which shows t...","[-19.490333557128906, -9.05998420715332, -9.74...",What is the shape of the kidney in the picture?
4,1002,1.389995,0.378946,1.422438,14,"['The image is an abdominal MRI, which is a ma...","[-7.381757736206055, -5.320309638977051, -12.1...",What modality is used to take this image?

In [22]:
grounding_df.head()

,question_id,grounding_biomedclip,grounding_biomedclip_processed,grounding_llama32_11b,grounding_llama32_11b_processed,grounding_llama32_70b,grounding_llama32_70b_processed,grounding_qwen_vl,grounding_qwen_vl_processed
0,0,"[35.556427001953125, 32.47749328613281, 34.951...","[35.556427001953125, 32.47749328613281, 34.951...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes<|im_en...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye..."
1,2,"[28.62195587158203, 32.28140640258789, 37.2424...","[28.62195587158203, 32.28140640258789, 37.2424...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes<|im_en...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye..."
2,7,"[30.373842239379883, 30.618961334228516, 34.12...","[30.373842239379883, 30.618961334228516, 34.12...","['Yes.<|eot_id|>', 'No<|eot_id|>', 'No<|eot_id...","['yes', 'no', 'no', 'no', 'no', 'yes', 'no', '...","['Yes.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_...","['yes', 'no', 'no', 'no', 'no', 'yes', 'no', '...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes\nExpla...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye..."
3,9,"[28.566133499145508, 7.654238700866699, 28.255...","[28.566133499145508, 7.654238700866699, 28.255...","['No.<|eot_id|>', 'No.<|eot_id|>', 'Yes.<|eot_...","['no', 'no', 'yes', 'yes', 'yes', 'no', 'no', ...","['No<|eot_id|>', 'No<|eot_id|>', 'No.<|eot_id|...","['no', 'no', 'no', 'yes', 'no', 'no', 'no', 'n...","['Yes\nExplanation: The statement ""The main or...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye..."
4,10,"[26.50864601135254, 31.354907989501953, 36.290...","[26.50864601135254, 31.354907989501953, 36.290...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'yes', 'yes', 'no', '...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No<|eot_id...","['no', 'no', 'no', 'yes', 'no', 'no', 'no', 'y...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes\nExpla...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye..."

In [23]:
# get all the shapes of the dataframes
print('Acc Shape:', acc_df.shape)
print('Baseline Shape:', baseline_df.shape)
print('Grounding Shape:', grounding_df.shape)

Acc Shape: (1640, 2)
Baseline Shape: (1640, 8)
Grounding Shape: (1640, 9)

In [24]:
import ast

# Convert the string representation of the list to an actual list
grounding_df['grounding_biomedclip'] = grounding_df['grounding_biomedclip'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Calculate the max value for each list in the column
grounding_df['max_grounding_biomedclip'] = grounding_df['grounding_biomedclip'].apply(lambda x: max(x) if isinstance(x, list) else x)

# Display the updated dataframe

In [25]:
grounding_df['max_grounding_biomedclip'].max()

43.61283874511719

In [26]:
# merge the dataframes acc_df, baseline_df, grounding_df
merged_df = pd.merge(acc_df, baseline_df, on='question_id')
merged_df = pd.merge(merged_df, grounding_df, on='question_id')

merged_df.head()

,question_id,accuracy,predictive_entropy,lexical_similarity,semantic_entropy,num_clusters,responses,resp_log_probs,question,grounding_biomedclip,grounding_biomedclip_processed,grounding_llama32_11b,grounding_llama32_11b_processed,grounding_llama32_70b,grounding_llama32_70b_processed,grounding_qwen_vl,grounding_qwen_vl_processed,max_grounding_biomedclip
0,0,0.85,1.244401,0.371253,1.055891,14,"['The image is a T1-weighted MRI, which is a t...","[-18.569684982299805, -33.829524993896484, -7....",What modality is used to take this image?,"[35.556427001953125, 32.47749328613281, 34.951...","[35.556427001953125, 32.47749328613281, 34.951...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes<|im_en...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye...",40.913319
1,10,0.05,1.051882,0.359208,0.967955,15,['The image is a coronal view of an abdomen MR...,"[-22.405088424682617, -22.054996490478516, -6....",What is the largest organ in the picture?,"[26.50864601135254, 31.354907989501953, 36.290...","[26.50864601135254, 31.354907989501953, 36.290...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'yes', 'yes', 'no', '...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No<|eot_id...","['no', 'no', 'no', 'yes', 'no', 'no', 'no', 'y...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes\nExpla...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye...",36.533497
2,1000,0.10,0.881631,0.364706,0.684908,16,['The black hole in the upper right corner of ...,"[-4.018756866455078, -14.954319953918457, -24....",What organ is the black hole in the upper righ...,"[28.817378997802734, 27.706912994384766, 30.09...","[28.817378997802734, 27.706912994384766, 30.09...","['No<|eot_id|>', 'No<|eot_id|>', 'No<|eot_id|>...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['Yes.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_...","['yes', 'no', 'no', 'no', 'no', 'no', 'no', 'n...","['No\nExplanation: The statement ""The black ho...","['no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes...",31.421982
3,1001,0.00,1.194139,0.360086,1.011172,18,"['The image is an abdominal MRI, which shows t...","[-19.490333557128906, -9.05998420715332, -9.74...",What is the shape of the kidney in the picture?,"[20.098480224609375, 15.856243133544922, 25.76...","[20.098480224609375, 15.856243133544922, 25.76...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_i...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['No.<|eot_id|>', 'No.<|eot_id|>', 'No<|eot_id...","['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no...","['Yes<|im_end|>', 'Yes<|im_end|>', 'Yes<|im_en...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye...",27.043623
4,1002,0.25,1.389995,0.378946,1.422438,14,"['The image is an abdominal MRI, which is a ma...","[-7.381757736206055, -5.320309638977051, -12.1...",What modality is used to take this image?,"[24.439762115478516, 26.77223014831543, 17.459...","[24.439762115478516, 26.77223014831543, 17.459...","['Yes.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_...","['yes', 'no', 'no', 'no', 'no', 'no', 'yes', '...","['Yes.<|eot_id|>', 'No.<|eot_id|>', 'No.<|eot_...","['yes', 'no', 'no', 'no', 'no', 'no', 'no', 'y...","['Yes<|im_end|>', 'Yes\nExplanation: The state...","['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'ye...",35.079838

In [27]:
merged_df.columns

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip'],
      dtype='object')

In [29]:
# lets see how many nan values we have in the dataframe
merged_df.isna().sum() # can we remove the nan values rows 
merged_df = merged_df.dropna()

### Scale the baselines

In [30]:
# normalize 'predictive_entropy', 'lexical_similarity', 'semantic_entropy', 'num_clusters' and the baselines to be in the range of 0 to 1, based on the max value of each column
min_val = merged_df['predictive_entropy'].min()
max_val = merged_df['predictive_entropy'].max()
merged_df['predictive_entropy_min_max_scaled'] = (merged_df['predictive_entropy'] - min_val) / (max_val - min_val)

min_val = merged_df['lexical_similarity'].min()
max_val = merged_df['lexical_similarity'].max()
merged_df['lexical_similarity_min_max_scaled'] = (merged_df['lexical_similarity'] - min_val) / (max_val - min_val)

min_val = merged_df['semantic_entropy'].min()
max_val = merged_df['semantic_entropy'].max()
merged_df['semantic_entropy_min_max_scaled'] = (merged_df['semantic_entropy'] - min_val) / (max_val - min_val)

min_val = merged_df['num_clusters'].min()
max_val = merged_df['num_clusters'].max()
merged_df['num_clusters_min_max_scaled'] = (merged_df['num_clusters'] - min_val) / (max_val - min_val)

## Process the grounding values

### Biomedclip Scores

In [31]:
# Fill NaN values with an empty list
merged_df['grounding_biomedclip_processed'] = merged_df['grounding_biomedclip_processed'].fillna('[]')

# Convert strings to lists
grounding_lists = merged_df['grounding_biomedclip_processed'].apply(ast.literal_eval)

# Calculate the min value across all rows, ignoring empty lists
min_value = min((min(lst) for lst in grounding_lists if lst), default=0)
max_value = max((max(lst) for lst in grounding_lists if lst), default=0)

# Scale each value in the list accordingly
scaled_grounding_lists = grounding_lists.apply(lambda lst: [(x - min_value)/(max_val - min_val) for x in lst])

# Update the dataframe with the scaled values
merged_df['grounding_biomedclip_processed_scaled'] = scaled_grounding_lists.apply(str)

# Display the updated DataFrame
# print(merged_df)

In [32]:
merged_df['grounding_biomedclip_processed_scaled'].head()
merged_df['grounding_biomedclip_processed_scaled_average'] = merged_df['grounding_biomedclip_processed_scaled'].apply(lambda x: sum(ast.literal_eval(x))/len(ast.literal_eval(x)) if len(ast.literal_eval(x)) > 0 else 0)

In [33]:
### calculate how many yes for llama32_11b and llama32_90b 
# Calculate the score based on the number of "yes" responses
def calculate_yes_score(response_list):
    if not response_list or pd.isna(response_list):
        return 0
    responses = ast.literal_eval(response_list)
    yes_count = responses.count("yes")
    total_count = len(responses)
    return yes_count / total_count if total_count > 0 else 0

merged_df['grounding_llama32_11b_processed_score'] = merged_df['grounding_llama32_11b_processed'].apply(calculate_yes_score)
merged_df['grounding_llama32_70b_processed_score'] = merged_df['grounding_llama32_70b_processed'].apply(calculate_yes_score)
merged_df['grounding_qwen_vl_processed_score'] = merged_df['grounding_qwen_vl_processed'].apply(calculate_yes_score)

In [34]:
merged_df.columns

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
       'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
       'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
       'grounding_biomedclip_processed_scaled_average',
       'grounding_llama32_11b_processed_score',
       'grounding_llama32_70b_processed_score',
       'grounding_qwen_vl_processed_score'],
      dtype='object')

In [35]:
# Ramneets Method, based on grounding models confidence, 
# i have to check the agreement between the grounding models, lets say i take llama3.2v 11b and llama3.2v 70b,
# agrement, is how many times they agree on the grounding, both are list of yes, so i have to see how many times they agree on the yes or no, 

def calculate_agreement(response_list_1, response_list_2):
    if not response_list_1 or pd.isna(response_list_1) or not response_list_2 or pd.isna(response_list_2):
        return 0
    responses_1 = ast.literal_eval(response_list_1)
    responses_2 = ast.literal_eval(response_list_2)
    agreement = sum([1 for r1, r2 in zip(responses_1, responses_2) if r1 == r2])
    total_count = len(responses_1)
    return agreement / total_count if total_count > 0 else 0

# Apply the calculate_agreement function to each row
merged_df['grounding_llama32_11b_llama32_70b_agreement'] = merged_df.apply(
    lambda row: calculate_agreement(row['grounding_llama32_11b_processed'], row['grounding_llama32_70b_processed']),
    axis=1
)

In [36]:
merged_df['grounding_llama32_11b_llama32_70b_agreement'].head()

0    1.00
1    0.80
2    0.90
3    1.00
4    0.95
Name: grounding_llama32_11b_llama32_70b_agreement, dtype: float64

In [37]:
# agreement between llama32_11b and qwen_vl
merged_df['grounding_llama32_11b_qwen_vl_agreement'] = merged_df.apply(
    lambda row: calculate_agreement(row['grounding_llama32_11b_processed'], row['grounding_qwen_vl_processed']),
    axis=1
)

# agreement between llama32_70b and qwen_vl
merged_df['grounding_llama32_70b_qwen_vl_agreement'] = merged_df.apply(
    lambda row: calculate_agreement(row['grounding_llama32_70b_processed'], row['grounding_qwen_vl_processed']),
    axis=1
)

In [38]:
merged_df.columns

# Index(['question_id', 'predictive_entropy', 'lexical_similarity',
#        'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
#        'question', 'accuracy', 'grounding_biomedclip',
#        'grounding_biomedclip_processed', 'grounding_llama32_11b',
#        'grounding_llama32_11b_processed', 'grounding_llama32_70b',
#        'grounding_llama32_70b_processed', 'grounding_qwen_vl',
#        'grounding_qwen_vl_processed', 'predictive_entropy_min_max_scaled',
#        'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
#        'num_clusters_min_max_scaled', 'grounding_biomedclip_scaled',
#        'grounding_biomedclip_processed_scaled',
#        'grounding_llama32_11b_processed_score',
#        'grounding_llama32_70b_processed_score',
#        'grounding_qwen_vl_processed_score',
#        'grounding_llama32_11b_llama32_70b_agreement',
#        'grounding_llama32_11b_qwen_vl_agreement',
#        'grounding_llama32_70b_qwen_vl_agreement'],
#       dtype='object')

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
       'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
       'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
       'grounding_biomedclip_processed_scaled_average',
       'grounding_llama32_11b_processed_score',
       'grounding_llama32_70b_processed_score',
       'grounding_qwen_vl_processed_score',
       'grounding_llama32_11b_llama32_70b_agreement',
       'grounding_llama32_11b_qwen_vl_agreement',
       'grounding_llama32_70b_qwen_vl_agreement'],
      dtype='object')

In [39]:
merged_df.head()

,question_id,accuracy,predictive_entropy,lexical_similarity,semantic_entropy,num_clusters,responses,resp_log_probs,question,grounding_biomedclip,...,semantic_entropy_min_max_scaled,num_clusters_min_max_scaled,grounding_biomedclip_processed_scaled,grounding_biomedclip_processed_scaled_average,grounding_llama32_11b_processed_score,grounding_llama32_70b_processed_score,grounding_qwen_vl_processed_score,grounding_llama32_11b_llama32_70b_agreement,grounding_llama32_11b_qwen_vl_agreement,grounding_llama32_70b_qwen_vl_agreement
0,0,0.85,1.244401,0.371253,1.055891,14,"['The image is a T1-weighted MRI, which is a t...","[-18.569684982299805, -33.829524993896484, -7....",What modality is used to take this image?,"[35.556427001953125, 32.47749328613281, 34.951...",...,0.567021,0.600000,"[2.1422053654988606, 1.9369431177775065, 2.101...",2.052948,0.00,0.00,1.0,1.00,0.00,0.00
1,10,0.05,1.051882,0.359208,0.967955,15,['The image is a coronal view of an abdomen MR...,"[-22.405088424682617, -22.054996490478516, -6....",What is the largest organ in the picture?,"[26.50864601135254, 31.354907989501953, 36.290...",...,0.519793,0.666667,"[1.5390199661254882, 1.862104098002116, 2.1911...",1.764599,0.25,0.15,1.0,0.80,0.25,0.15
2,1000,0.10,0.881631,0.364706,0.684908,16,['The black hole in the upper right corner of ...,"[-4.018756866455078, -14.954319953918457, -24....",What organ is the black hole in the upper righ...,"[28.817378997802734, 27.706912994384766, 30.09...",...,0.367776,0.733333,"[1.6929354985555014, 1.61890443166097, 1.77821...",1.453190,0.05,0.05,0.9,0.90,0.05,0.05
3,1001,0.00,1.194139,0.360086,1.011172,18,"['The image is an abdominal MRI, which shows t...","[-19.490333557128906, -9.05998420715332, -9.74...",What is the shape of the kidney in the picture?,"[20.098480224609375, 15.856243133544922, 25.76...",...,0.543003,0.866667,"[1.1116755803426106, 0.8288597742716471, 1.489...",1.241851,0.05,0.05,1.0,1.00,0.05,0.05
4,1002,0.25,1.389995,0.378946,1.422438,14,"['The image is an abdominal MRI, which is a ma...","[-7.381757736206055, -5.320309638977051, -12.1...",What modality is used to take this image?,"[24.439762115478516, 26.77223014831543, 17.459...",...,0.763883,0.600000,"[1.40109437306722, 1.5565922419230143, 0.93575...",1.404151,0.20,0.15,1.0,0.95,0.20,0.15

In [41]:
import math

def item_level_entropy_3lists(list1, list2, list3):
    """
    For each of the 20 positions, count how many 'yes' among the 3 lists.
    Compute binary entropy of that mini-distribution (p_yes, p_no).
    Then average across the 20 items.
    """
    n = len(list1)  # assume each list has the same length, e.g. 20
    total_entropy = 0.0
    
    for i in range(n):
        # yes_count for item i across the 3 lists
        yes_count = sum(lst[i].lower() == 'yes' for lst in [list1, list2, list3])
        p_i = yes_count / 3.0
        
        if p_i == 0 or p_i == 1:
            H_i = 0.0
        else:
            H_i = - (p_i * math.log2(p_i) + (1 - p_i) * math.log2(1 - p_i))
        
        total_entropy += H_i
    
    # Average entropy across the 20 items
    return total_entropy / n

import math

def item_level_entropy_2experts(expert1_responses, expert2_responses):
    """
    Computes average binary entropy across items, where each item has
    'yes'/'no' from two experts.

    - expert1_responses: list of length N, each "yes" or "no"
    - expert2_responses: list of length N, each "yes" or "no"

    Returns a float: average binary entropy across the N items.

    For each item i:
      - p_i = (#yes among 2 experts) / 2
      - H_i = -[p_i log2(p_i) + (1 - p_i) log2(1 - p_i)] (0 if p_i=0 or 1)
    Then we average H_i over all items.
    """
    n = len(expert1_responses)
    total_entropy = 0.0
    
    for i in range(n):
        yes_count = 0
        if expert1_responses[i].lower() == "yes":
            yes_count += 1
        if expert2_responses[i].lower() == "yes":
            yes_count += 1
        
        p_i = yes_count / 2.0
        
        if p_i == 0 or p_i == 1:
            H_i = 0.0
        else:
            H_i = -(p_i * math.log2(p_i) + (1 - p_i) * math.log2(1 - p_i))
        
        total_entropy += H_i
    
    avg_entropy = total_entropy / n
    return avg_entropy
def item_level_entropy_3experts(expert1_responses, expert2_responses, expert3_responses):
    """
    Compute the average binary entropy across items, where each item has 3 'yes'/'no' votes
    from three experts.
    
    - expert1_responses: list of length N (e.g., 20), each either "yes" or "no"
    - expert2_responses: list of length N, each either "yes" or "no"
    - expert3_responses: list of length N, each either "yes" or "no"
    
    Returns the average binary entropy: 
        - For each item i, we compute the fraction p_i = (#yes among the 3 experts) / 3
        - Then we compute the binary entropy H_i = -[p_i log2(p_i) + (1-p_i) log2(1-p_i)]
          (with 0 if p_i=0 or 1)
        - Finally, we average H_i across all items.
    """
    # Assume all lists have the same length
    n = len(expert1_responses)
    total_entropy = 0.0
    
    for i in range(n):
        # Count how many experts said "yes"
        yes_count = 0
        if expert1_responses[i].lower() == "yes":
            yes_count += 1
        if expert2_responses[i].lower() == "yes":
            yes_count += 1
        if expert3_responses[i].lower() == "yes":
            yes_count += 1

        # Fraction that said "yes"
        p_i = yes_count / 3.0
        
        # Compute binary entropy
        if p_i == 0 or p_i == 1:
            H_i = 0.0
        else:
            H_i = -(p_i * math.log2(p_i) + (1 - p_i) * math.log2(1 - p_i))
        
        total_entropy += H_i
    
    # Average entropy across all items
    avg_entropy = total_entropy / n
    return avg_entropy

# Apply the item_level_entropy_3lists function to 'grounding_llama32_11b_processed','grounding_llama32_70b_processed', 'grounding_qwen_vl_processed',

merged_df['grounding_models_entropy_llama11b_llama70b_qwenvl'] = merged_df.apply( lambda row: item_level_entropy_3lists(ast.literal_eval(row['grounding_llama32_11b_processed']), ast.literal_eval(row['grounding_llama32_70b_processed']), ast.literal_eval(row['grounding_qwen_vl_processed'])), axis=1)
# merged_df['grounding_models_entropy_llama11b_llama70b_qwenvl'].head(
    
# now caclaute the entropy between llama32_11b and llama32_70b
merged_df['grounding_models_entropy_llama11b_llama70b'] = merged_df.apply( lambda row: item_level_entropy_2experts(ast.literal_eval(row['grounding_llama32_11b_processed']), ast.literal_eval(row['grounding_llama32_70b_processed'])), axis=1)

# now caclaute the entropy between llama32_11b and qwen_vl
merged_df['grounding_models_entropy_llama11b_qwenvl'] = merged_df.apply( lambda row: item_level_entropy_2experts(ast.literal_eval(row['grounding_llama32_11b_processed']), ast.literal_eval(row['grounding_qwen_vl_processed'])), axis=1)

# now caclaute the entropy between llama32_70b and qwen_vl
merged_df['grounding_models_entropy_llama70b_qwenvl'] = merged_df.apply( lambda row: item_level_entropy_2experts(ast.literal_eval(row['grounding_llama32_70b_processed']), ast.literal_eval(row['grounding_qwen_vl_processed'])), axis=1)

In [42]:
merged_df.columns

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
       'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
       'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
       'grounding_biomedclip_processed_scaled_average',
       'grounding_llama32_11b_processed_score',
       'grounding_llama32_70b_processed_score',
       'grounding_qwen_vl_processed_score',
       'grounding_llama32_11b_llama32_70b_agreement',
       'grounding_llama32_11b_qwen_vl_agreement',
       'grounding_llama32_70b_qwen_vl_agreement',
       'grounding_models_entropy_llama11b_llama70b_qwenvl',
       'grounding_models_entropy_llama11b_llama70b',
       'grounding_models_entropy_llama11b_qwenvl',
       'grounding_models_entropy_llama70b_qwenvl'],
      dtype='object')

In [43]:
merged_df.to_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed.csv', index=False)

In [3]:
# merged_df.columns

### On feb 6, it was decided to also find the uncertainty of the grounding model

In [7]:
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import ast
df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed.csv')

In [2]:
df.columns

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
       'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
       'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
       'grounding_biomedclip_processed_scaled_average',
       'grounding_llama32_11b_processed_score',
       'grounding_llama32_70b_processed_score',
       'grounding_qwen_vl_processed_score',
       'grounding_llama32_11b_llama32_70b_agreement',
       'grounding_llama32_11b_qwen_vl_agreement',
       'grounding_llama32_70b_qwen_vl_agreement',
       'grounding_models_entropy_llama11b_llama70b_qwenvl',
       'grounding_models_entropy_llama11b_llama70b',
       'grounding_models_entropy_llama11b_qwenvl',
       'grounding_models_entropy_llama70b_qwenvl'],
      dtype='object')

In [3]:
import torch

def are_semantically_equivalent(respA, respB, question, tokenizer, model, device='cpu'):
    """
    Checks if respA and respB are mutually entailing given the question context.
    Returns True if label=2 in both directions, else False.
    """

    premise_forward  = f"{respA}"
    hypothesis_fwd   = f"{respB}"

    premise_backward = f"{respB}"
    hypothesis_bwd   = f"{respA}"

    # Forward pass
    inputs_f = tokenizer.encode_plus(
        premise_forward, hypothesis_fwd, 
        return_tensors='pt', truncation=True
    )
    inputs_f = {k: v.to(device) for k, v in inputs_f.items()}
    with torch.no_grad():
        logits_f = model(**inputs_f).logits
    label_f = torch.argmax(logits_f, dim=1).item()  # e.g. 0/1/2

    # Backward pass
    inputs_b = tokenizer.encode_plus(
        premise_backward, hypothesis_bwd, 
        return_tensors='pt', truncation=True
    )
    inputs_b = {k: v.to(device) for k, v in inputs_b.items()}
    with torch.no_grad():
        logits_b = model(**inputs_b).logits
    label_b = torch.argmax(logits_b, dim=1).item()

    # Check mutual entailment
    return (label_f == 2) and (label_b == 2)

In [10]:
def cal_entropy_grounding_semantic(row, tokenizer, model, device='cpu'):
    responses = ast.literal_eval(row["responses"])
    groundings= ast.literal_eval(row["grounding_llama32_70b_processed"])
    question  = row["question"]  # if you stored it in the row
    n = len(responses)
    if n == 0 or len(groundings) != n:
        return 0.0

    # Build adjacency with mutual entailment
    adjacency = [[False]*n for _ in range(n)]
    for i in range(n):
        for j in range(i+1, n):
            # check if responses i and j are semantically equivalent
            if are_semantically_equivalent(
                   responses[i], responses[j], 
                   question, 
                   tokenizer, 
                   model, 
                   device=device
               ):
                adjacency[i][j] = True
                adjacency[j][i] = True

    # Then BFS cluster, same logic as before
    visited = [False]*n
    clusters = []
    for i in range(n):
        if not visited[i]:
            stack = [i]
            visited[i] = True
            cluster_members = []
            while stack:
                node = stack.pop()
                cluster_members.append(node)
                for nb in range(n):
                    if adjacency[node][nb] and not visited[nb]:
                        visited[nb] = True
                        stack.append(nb)
            clusters.append(cluster_members)

    # Compute grounding entropy
    grounding_score_with_entropy = []
    for c in clusters:
        cluster_size = len(c)
        yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
        p = yes_count / cluster_size

        if p == 0 or p == 1:
            h_cluster = 0.0
        else:
            h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

        # lets take the grounding score of the cluster, no of yes in the cluster / total no of responses in the cluster
        no_of_yes_in_cluster = sum(1 for idx in c if groundings[idx].lower() == "yes")
        cluster_size = len(c)
        grounding_score = no_of_yes_in_cluster / cluster_size
        grounding_score_of_the_cluster = grounding_score * h_cluster
        # weighted_sum += grounding_score_of_the_cluster
        grounding_score_with_entropy.append(grounding_score_of_the_cluster)
        
    return sum(grounding_score_with_entropy) / len(grounding_score_with_entropy)

In [14]:
import math
import ast

def cal_entropy_grounding_semantic_debug(row, tokenizer, model, device='cpu'):
    """
    Computes grounding entropy by clustering responses based on semantic equivalence.
    This version prints all intermediate outputs for debugging.

    Args:
        row (dict): Dictionary containing:
            - "responses" (list): List of generated responses.
            - "grounding_llama32_70b_processed" (list): Corresponding "Yes" or "No" groundings.
            - "question" (str): The original question prompting these responses.
        tokenizer: Pre-trained tokenizer.
        model: Pre-trained entailment model.
        device (str): "cpu" or "cuda".

    Returns:
        float: Final grounding score with entropy.
    """

    # Parse responses & groundings from row data
    responses = ast.literal_eval(row["responses"])
    groundings = ast.literal_eval(row["grounding_llama32_70b_processed"])
    question = row["question"]
    n = len(responses)

    # Handle edge case: No responses or mismatched groundings
    if n == 0 or len(groundings) != n:
        print("No valid responses or mismatch between responses and groundings.")
        return 0.0

    print(f"\n--- Question: {question} ---")
    print("Responses:", responses)
    print("Groundings:", groundings)

    # ---- STEP 1: Build Adjacency Matrix for Semantic Clustering ----
    adjacency = [[False] * n for _ in range(n)]

    print("\nBuilding adjacency matrix using entailment...")

    for i in range(n):
        for j in range(i + 1, n):
            if are_semantically_equivalent(responses[i], responses[j], question, tokenizer, model, device=device):
                adjacency[i][j] = adjacency[j][i] = True

    print("Adjacency Matrix:")
    for row in adjacency:
        print(row)

    # ---- STEP 2: Cluster Responses Using BFS ----
    visited = [False] * n
    clusters = []

    print("\nClustering responses using BFS...")

    for i in range(n):
        if not visited[i]:
            stack = [i]
            visited[i] = True
            cluster_members = []

            while stack:
                node = stack.pop()
                cluster_members.append(node)
                for nb in range(n):
                    if adjacency[node][nb] and not visited[nb]:
                        visited[nb] = True
                        stack.append(nb)

            clusters.append(cluster_members)

    print("\nClusters formed:")
    for idx, cluster in enumerate(clusters):
        print(f"Cluster {idx+1}: {[responses[i] for i in cluster]}")

    # ---- STEP 3: Compute Grounding Entropy per Cluster ----
    grounding_scores_with_entropy = []

    print("\nComputing grounding entropy per cluster...")

    for idx, cluster in enumerate(clusters):
        cluster_size = len(cluster)
        yes_count = sum(1 for i in cluster if groundings[i].lower() == "yes")

        # Compute probability of "Yes" in cluster
        p = yes_count / cluster_size if cluster_size > 0 else 0

        # Compute Shannon entropy, handling edge cases
        if p in [0, 1]:  # No uncertainty in cluster
            h_cluster = 0.0
        else:
            h_cluster = - (p * math.log2(p) + (1 - p) * math.log2(1 - p))

        # Compute grounding score (fraction of "Yes" responses)
        grounding_score = yes_count / cluster_size if cluster_size > 0 else 0

        # Compute uncertainty-weighted grounding score
        grounding_score_with_entropy = grounding_score * h_cluster
        grounding_scores_with_entropy.append(grounding_score_with_entropy)

        # Print debug information
        print(f"\nCluster {idx+1}:")
        print(f"  Responses: {[responses[i] for i in cluster]}")
        print(f"  Groundings: {[groundings[i] for i in cluster]}")
        print(f"  Yes Count: {yes_count}, Total: {cluster_size}, P(Yes): {p:.4f}")
        print(f"  Entropy: {h_cluster:.4f}")
        print(f"  Grounding Score: {grounding_score:.4f}")
        print(f"  Weighted Grounding Score: {grounding_score_with_entropy:.4f}")

    # Compute final score using weighted sum
    final_score = sum(grounding_scores_with_entropy) / len(grounding_scores_with_entropy) if grounding_scores_with_entropy else 0.0

    print("\nFinal Grounding Score with Entropy:", final_score)
    return final_score

In [19]:
# Test Case 1: Perfect Agreement (All “Yes”)
test_case_1 = {
    "responses": str([
        "The image shows a cat sitting on a chair.",
        "A cat is sitting on the chair.",
        "There is a cat sitting on a wooden chair."
    ]),
    "grounding_llama32_70b_processed": str(["Yes", "Yes", "Yes"]),
    "question": "Does the image contain a cat sitting on a chair?"
}

# 🔹 Test Case 2: Total Disagreement (All “No”)
test_case_2 = {
    "responses": str([
        "The image shows a blue car parked outside.",
        "There is a red car in the image.",
        "A sports car is visible in the frame."
    ]),
    "grounding_llama32_70b_processed": str(["No", "No", "No"]),
    "question": "Does the image contain a bicycle?"
}

# 🔹 Test Case 3: Maximum Uncertainty (50-50 Split)
test_case_3 = {
    "responses": str([
        "There is a dog lying on the grass.",
        "A dog is resting in a park.",
        "The image shows a brown dog on the lawn.",
        "There is no dog in the image.",
        "The image contains only a tree and some grass."
    ]),
    "grounding_llama32_70b_processed": str(["Yes", "Yes", "Yes", "No", "No"]),
    "question": "Is there a dog in the image?"
}

# 🔹 Test Case 4: Single Large Cluster with Uncertainty
test_case_4 = {
    "responses": str([
        "There is a cat sitting next to a bowl.",
        "A small kitten is next to a food bowl.",
        "A white cat is near a silver bowl.",
        "A cat and a dog are in the image.",
        "There is a dog, but no cat."
    ]),
    "grounding_llama32_70b_processed": str(["Yes", "Yes", "Yes", "No", "No"]),
    "question": "Is there a cat near a bowl?"
}

# 🔹 Test Case 5: Multiple Small Clusters (Varied Uncertainty)
test_case_5 = {
    "responses": str([
        "A red bus is visible on the street.",      # Cluster 1 (Yes)
        "There is a red double-decker bus.",       # Cluster 1 (Yes)
        "A blue car is in the center of the road.",# Cluster 2 (No)
        "A vehicle with blue paint is present.",   # Cluster 2 (No)
        "A truck is parked near a shop."           # Cluster 3 (Uncertain)
    ]),
    "grounding_llama32_70b_processed": str(["Yes", "Yes", "No", "No", "Not sure"]),
    "question": "Is there a red bus in the image?"
}

# 🔹 Test Case 6: Edge Case (Only One Response)
test_case_6 = {
    "responses": str(["A person is riding a bicycle."]),
    "grounding_llama32_70b_processed": str(["Yes"]),
    "question": "Is there a bicycle in the image?"
}

test_cases = [test_case_1, test_case_2, test_case_3, test_case_4, test_case_5, test_case_6]

model_name  = 'microsoft/deberta-base-mnli'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
for i, test_case in enumerate(test_cases):
    # result = cal_entropy_grounding_semantic(test_case, tokenizer, model, device='cpu')
    result = cal_entropy_grounding_semantic_debug(test_case, tokenizer, model, device='cpu')
    print(f"Test Case {i+1} - Grounding Score with Entropy: {result}")

Some weights of the model checkpoint at microsoft/deberta-base-mnli were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

--- Question: Does the image contain a cat sitting on a chair? ---
Responses: ['The image shows a cat sitting on a chair.', 'A cat is sitting on the chair.', 'There is a cat sitting on a wooden chair.']
Groundings: ['Yes', 'Yes', 'Yes']

Building adjacency matrix using entailment...

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

In [ ]:
# ok lets do it for the whole dataframe
from tqdm import tqdm

# Enable tqdm for pandas
tqdm.pandas()

model_name  = 'microsoft/deberta-base-mnli'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
# df['grounding_llama32V_with_cluster_wise_entropy'] = df.progress_apply(lambda row: cal_entropy_grounding_semantic(row, tokenizer, model, device='cuda'), axis=1)

# from joblib import Parallel, delayed

# def process_row(row, tokenizer, model, device):
#     return cal_entropy_grounding_semantic(row, tokenizer, model, device)

# num_gpus = torch.cuda.device_count()
# df["grounding_llama32V_with_cluster_wise_entropy"] = Parallel(n_jobs=num_gpus)(
#     delayed(process_row)(row, tokenizer, model, f"cuda:{i % num_gpus}") for i, row in enumerate(df.iterrows())
)

Some weights of the model checkpoint at microsoft/deberta-base-mnli were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/home/tpadhi1/miniconda3/envs/llava_test/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/home/tpadhi1/miniconda3/envs/llava_test/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/home/tpadhi1/miniconda3/envs/llava_test/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/home/tpadhi1/miniconda3/envs/llava_test/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

TypeError: tuple indices must be integers or slices, not str

:

In [2]:
# def cal_entropy_grounding_semantic(row, tokenizer, model, device='cpu'):
#     responses = ast.literal_eval(row["responses"])
#     groundings= ast.literal_eval(row["grounding_llama32_70b_processed"])
#     question  = row["question"]  # if you stored it in the row
#     n = len(responses)
#     if n == 0 or len(groundings) != n:
#         return 0.0

#     # Build adjacency with mutual entailment
#     adjacency = [[False]*n for _ in range(n)]
#     for i in range(n):
#         for j in range(i+1, n):
#             # check if responses i and j are semantically equivalent
#             if are_semantically_equivalent(
#                    responses[i], responses[j], 
#                    question, 
#                    tokenizer, 
#                    model, 
#                    device=device
#                ):
#                 adjacency[i][j] = True
#                 adjacency[j][i] = True

#     # Then BFS cluster, same logic as before
#     visited = [False]*n
#     clusters = []
#     for i in range(n):
#         if not visited[i]:
#             stack = [i]
#             visited[i] = True
#             cluster_members = []
#             while stack:
#                 node = stack.pop()
#                 cluster_members.append(node)
#                 for nb in range(n):
#                     if adjacency[node][nb] and not visited[nb]:
#                         visited[nb] = True
#                         stack.append(nb)
#             clusters.append(cluster_members)

#     # Then compute the cluster-level grounding entropy as before
#     total_entropy = 0.0
#     for c in clusters:
#         cluster_size = len(c)
#         yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
#         p = yes_count / cluster_size

#         if p == 0 or p == 1:
#             h_cluster = 0.0
#         else:
#             h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

#         weight = cluster_size / n
#         total_entropy += weight * h_cluster

#     return total_entropy

In [14]:
# import math
# import numpy as np
# import pandas as pd

# def cal_entropy_grounding(row):
#     """
#     For each row:
#       1) Cluster the row's responses (here, we do a simple 'identical text' check 
#          but you can swap in your BFS-based mutual entailment logic).
#       2) For each cluster, compute fraction of "yes" from 'grounding_llama32_70b_processed'.
#       3) Compute binary entropy for that fraction.
#       4) Weight each cluster's entropy by cluster size / total responses, and sum.

#     Returns a single scalar "entropy_grounding" for this row.
#     """

#     responses  = ast.literal_eval(row["responses"])                      # list of (up to) 20 responses
#     groundings = ast.literal_eval(row["grounding_llama32_70b_processed"]) # list of "yes"/"no" of same length

#     # Edge case: if no responses or mismatch in lengths
#     n = len(responses)
#     if n == 0 or len(groundings) != n:
#         return 0.0

#     #-----------------------------------------
#     # 1) Build adjacency matrix for clustering
#     #    (Here we do a trivial "identical string" check.
#     #     For semantic BFS, you'd replace this with mutual entailment checks.)
#     #-----------------------------------------
#     adjacency = [[False]*n for _ in range(n)]
#     for i in range(n):
#         for j in range(i+1, n):
#             # Replace this condition with your "are_semantically_equivalent" check
#             if responses[i] == responses[j]:
#                 adjacency[i][j] = True
#                 adjacency[j][i] = True

#     #-----------------------------------------
#     # 2) Cluster using BFS/DFS
#     #-----------------------------------------
#     visited = [False]*n
#     clusters = []
#     for i in range(n):
#         if not visited[i]:
#             stack = [i]
#             visited[i] = True
#             cluster_members = []
#             while stack:
#                 node = stack.pop()
#                 cluster_members.append(node)
#                 for nb in range(n):
#                     if adjacency[node][nb] and not visited[nb]:
#                         visited[nb] = True
#                         stack.append(nb)
#             clusters.append(cluster_members)

#     #-----------------------------------------
#     # 3) For each cluster, compute fraction(yes) => binary entropy => sum
#     #    Weighted by cluster size / total size
#     #-----------------------------------------
#     total_entropy = 0.0
#     for c in clusters:
#         cluster_size = len(c)
#         yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
#         p = yes_count / cluster_size

#         # Binary entropy H(p):
#         if p == 0 or p == 1:
#             h_cluster = 0.0
#         else:
#             h_cluster = - (p * math.log2(p) + (1 - p) * math.log2(1 - p))

#         # Weight by fraction of total responses
#         weight = cluster_size / n
#         total_entropy += weight * h_cluster

#     return total_entropy


# # -------------------------------
# # EXAMPLE USAGE
# # -------------------------------

# # Suppose df has columns:
# # "responses" -> list of up to 20 strings
# # "grounding_llama32_70b_processed" -> list of "yes"/"no", same length as "responses"

# df["entropy_grounding_llama32_70b_processed"] = df.apply(cal_entropy_grounding, axis=1)

# def cal_entropy_grounding_semantic(row, tokenizer, model, device='cpu'):
#     responses = ast.literal_eval(row["responses"])
#     groundings= ast.literal_eval(row["grounding_llama32_70b_processed"])
#     question  = row["question"]  # if you stored it in the row
#     n = len(responses)
#     if n == 0 or len(groundings) != n:
#         return 0.0

#     # Build adjacency with mutual entailment
#     adjacency = [[False]*n for _ in range(n)]
#     for i in range(n):
#         for j in range(i+1, n):
#             # check if responses i and j are semantically equivalent
#             if are_semantically_equivalent(
#                    responses[i], responses[j], 
#                    question, 
#                    tokenizer, 
#                    model, 
#                    device=device
#                ):
#                 adjacency[i][j] = True
#                 adjacency[j][i] = True

#     # Then BFS cluster, same logic as before
#     visited = [False]*n
#     clusters = []
#     for i in range(n):
#         if not visited[i]:
#             stack = [i]
#             visited[i] = True
#             cluster_members = []
#             while stack:
#                 node = stack.pop()
#                 cluster_members.append(node)
#                 for nb in range(n):
#                     if adjacency[node][nb] and not visited[nb]:
#                         visited[nb] = True
#                         stack.append(nb)
#             clusters.append(cluster_members)

#     # Then compute the cluster-level grounding entropy as before
#     total_entropy = 0.0
#     for c in clusters:
#         cluster_size = len(c)
#         yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
#         p = yes_count / cluster_size

#         if p == 0 or p == 1:
#             h_cluster = 0.0
#         else:
#             h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

#         weight = cluster_size / n
#         total_entropy += weight * h_cluster

#     return total_entropy

def cal_entropy_grounding_semantic(row, tokenizer, model, device='cpu'):
    responses = ast.literal_eval(row["responses"])
    groundings= ast.literal_eval(row["grounding_llama32_70b_processed"])
    question  = row["question"]  # if you stored it in the row
    n = len(responses)
    if n == 0 or len(groundings) != n:
        return 0.0

    # Build adjacency with mutual entailment
    adjacency = [[False]*n for _ in range(n)]
    for i in range(n):
        for j in range(i+1, n):
            # check if responses i and j are semantically equivalent
            if are_semantically_equivalent(
                   responses[i], responses[j], 
                   question, 
                   tokenizer, 
                   model, 
                   device=device
               ):
                adjacency[i][j] = True
                adjacency[j][i] = True

    # Then BFS cluster, same logic as before
    visited = [False]*n
    clusters = []
    for i in range(n):
        if not visited[i]:
            stack = [i]
            visited[i] = True
            cluster_members = []
            while stack:
                node = stack.pop()
                cluster_members.append(node)
                for nb in range(n):
                    if adjacency[node][nb] and not visited[nb]:
                        visited[nb] = True
                        stack.append(nb)
            clusters.append(cluster_members)

    # # Then compute the cluster-level grounding entropy as before
    # total_entropy = 0.0
    # for c in clusters:
    #     cluster_size = len(c)
    #     yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
    #     p = yes_count / cluster_size

    #     if p == 0 or p == 1:
    #         h_cluster = 0.0
    #     else:
    #         h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

    #     weight = cluster_size / n
    #     total_entropy += weight * h_cluster
    # weighted_sum = 0.0
    grounding_score_with_entropy = []
    for c in clusters:
        cluster_size = len(c)
        yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
        p = yes_count / cluster_size

        if p == 0 or p == 1:
            h_cluster = 0.0
        else:
            h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

        # lets take the grounding score of the cluster, no of yes in the cluster / total no of responses in the cluster
        no_of_yes_in_cluster = sum(1 for idx in c if groundings[idx].lower() == "yes")
        cluster_size = len(c)
        grounding_score = no_of_yes_in_cluster / cluster_size
        grounding_score_of_the_cluster = grounding_score * h_cluster
        # weighted_sum += grounding_score_of_the_cluster
        grounding_score_with_entropy.append(grounding_score_of_the_cluster)

    return grounding_score_with_entropy.mean()

In [ ]:
test_case_1 = {
    "responses": str([
        "The image shows a cat sitting on a chair.",
        "A cat is sitting on the chair.",
        "There is a cat sitting on a wooden chair."
    ]),
    "grounding_llama32_70b_processed": str(["Yes", "Yes", "Yes"]),
    "question": "Does the image contain a cat sitting on a chair?"
}

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
# initialize deberta model and tokenizer 

model_name  = 'microsoft/deberta-base-mnli'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)
model.eval()  # Set model to evaluation mode

Some weights of the model checkpoint at microsoft/deberta-base-mnli were not used when initializing DebertaForSequenceClassification: ['config']
- This IS expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DebertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

DebertaForSequenceClassification(
  (deberta): DebertaModel(
    (embeddings): DebertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=0)
      (LayerNorm): DebertaLayerNorm()
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): DebertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x DebertaLayer(
          (attention): DebertaAttention(
            (self): DisentangledSelfAttention(
              (in_proj): Linear(in_features=768, out_features=2304, bias=False)
              (pos_dropout): Dropout(p=0.1, inplace=False)
              (pos_proj): Linear(in_features=768, out_features=768, bias=False)
              (pos_q_proj): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): DebertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): DebertaLayerNorm()
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): DebertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): DebertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): DebertaLayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (rel_embeddings): Embedding(1024, 768)
    )
  )
  (pooler): ContextPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0, inplace=False)
  )
  (classifier): Linear(in_features=768, out_features=3, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [15]:
## check if the function semantically_equivalent works for a pair of responses
respA = 'yes the capital of france is paris'
respB = 'paris is the capital of france'

are_semantically_equivalent(respA, respB, None, tokenizer, model, device)

True

In [20]:
# lets see the responses and the grounding for the first row
row = df.iloc[0]
responses = ast.literal_eval(row["responses"])
groundings= ast.literal_eval(row["grounding_llama32_70b_processed"])

print("Responses:")
for r in responses:
    print(f"  - {r}, {groundings[responses.index(r)]}")

Responses:
  - The image is a T1-weighted MRI, which is a type of magnetic resonance imaging that uses a specific pulse sequence to generate images with different contrasts. In this case, the image is focused on the abdomen, and the main organ visible is the lung and spinal cord., no
  - The image is an MRI scan of the abdomen, which shows a large mass in the left kidney. The mass is well-defined and has a complex internal structure. It is important to note that further evaluation and tests would be needed to determine the exact nature and cause of the mass., no
  - The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main organ in the image is the lung, which is part of the respiratory system. The spinal cord is also visible in the image, as it is located within the vertebral column in the abdominal region., no
  - The image is a T2-weighted MRI of the abdomen, focusing on the lung and spinal cord., no
  - The image is an MRI of the abdomen, showing the lung and spinal cord. The lung is a part of the respiratory system, while the spinal cord is a bundle of nerve fibers that connects the brain to the rest of the body., no
  - The image is a post-contrast MRI of the abdomen, which shows a mass in the left breast. The mass has a heterogeneous enhancement pattern, which means that the contrast agent used during the MRI highlights the mass in an irregular or uneven manner. This can be indicative of various types of lesions, such as cysts, fibroadenomas, or malignancies. Further evaluation and tests would be needed to determine the exact nature and cause of the mass., no
  - The MRI image shows a large, well-defined, and heterogeneous mass in the abdomen. This mass is displacing the Lung and Spinal Cord. The exact nature of the mass would require further analysis and clinical correlation to determine its cause and significance., no
  - The image is a T1-weighted MRI of the abdomen, focusing on the lung and spinal cord., no
  - The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main organs in the image are the lung and spinal cord, as they are the primary structures being examined., no
  - The image is a T2-weighted MRI of the abdomen, which shows a lobulated mass with internal septations in the left lung and spinal cord. This mass is associated with the patient's diagnosis of epithelioid hemangioendothelioma (EHE)., no
  - The image is a T1-weighted MRI of the abdomen. T1-weighted images are a type of MRI sequence that provides good anatomical detail and is often used to visualize the structure of organs and tissues. In this case, the image shows the Lung and Spinal Cord, which are two important organs in the abdomen., no
  - The main organ in the image is the Lung and Spinal Cord., no
  - The image is a T2-weighted MRI of the abdomen. It is a sagittal view, which means it is a side view of the body, showing the left and right sides of the abdomen. The main organ in the image is the Lung and Spinal Cord., no
  - The image is a cardiac MRI, which is a magnetic resonance imaging scan focused on the heart. Cardiac MRI is a non-invasive imaging technique that provides detailed information about the structure and function of the heart, including the chambers, valves, and surrounding blood vessels. It can help diagnose various heart conditions and guide treatment decisions., no
  - The main organ in the image is the lung., no
  - The image is an MRI of the abdomen, focusing on the lung and spinal cord. The main findings in the image are the presence of a large left pleural effusion and a large intraperitoneal mass, which is causing a mass effect on the spinal cord., no
  - The image is a T2-weighted MRI of the abdomen, which is a specific type of magnetic resonance imaging that provides detailed information about the tissues and organs within the abdominal cavity. In this case, the main organ in the image is the Lung and Spinal Cord., no
  - The image is a T2-weighted MRI of the abdomen, which includes the Lung and Spinal Cord., no
  - The image is a T2-weighted MRI of the abdomen, which includes the lung and spinal cord. T2-weighted images are a specific type of MRI sequence that provides detailed information about the tissue composition and can help visualize certain abnormalities or pathologies., no
  - The image is an MRI of the abdomen, and it shows a mass in the right lung and spinal cord. The mass is likely a metastasis, which is a secondary cancerous growth that has spread from another part of the body. In this case, the mass is located in the right lung and spinal cord., no

### Testing of the logic of the grounding model entropy if it works

In [16]:
# Now lets check the cal_entropy_grounding_semantic function for a row in the dataframe
import pandas as pd
import ast
df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed.csv')
df.columns

# Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
#        'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
#        'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
#        'grounding_llama32_11b', 'grounding_llama32_11b_processed',
#        'grounding_llama32_70b', 'grounding_llama32_70b_processed',
#        'grounding_qwen_vl', 'grounding_qwen_vl_processed',
#        'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
#        'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
#        'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
#        'grounding_biomedclip_processed_scaled_average',
#        'grounding_llama32_11b_processed_score',
#        'grounding_llama32_70b_processed_score',
#        'grounding_qwen_vl_processed_score',
#        'grounding_llama32_11b_llama32_70b_agreement',
#        'grounding_llama32_11b_qwen_vl_agreement',
#        'grounding_llama32_70b_qwen_vl_agreement',
#        'grounding_models_entropy_llama11b_llama70b_qwenvl',
#        'grounding_models_entropy_llama11b_llama70b',
#        'grounding_models_entropy_llama11b_qwenvl',
#        'grounding_models_entropy_llama70b_qwenvl'],
#       dtype='object')

# get the first row 
# before checking for a row, i want to check if for a sample of responses, the function works
responses = ast.literal_eval(df['responses'][0]) # lets not check anything from the dataset, but lets take a sample of dummy responses and check 
responses = ['yes the capital of france is paris', 'paris is the capital of france', 'no the capital of france is not paris', 'no paris is not the capital of france', 'yes the capital of france is paris', 'paris is the capital of france', 'no the capital of france is not paris', 'no paris is not the capital of france', 'yes the capital of france is paris', 'paris is the capital of france', 'no the capital of france is not paris', 'no paris is not the capital of france', 'yes the capital of france is paris', 'paris is the capital of france', 'no the capital of france is not paris', 'no paris is not the capital of france', 'yes the capital of france is paris', 'paris is the capital of france', 'no the capital of france is not paris', 'no paris is not the capital of france']

groundings= ast.literal_eval(df['grounding_llama32_70b_processed'][0])
question  = df['question'][0]  # if you stored it in the row
n = len(responses)

# Build adjacency with mutual entailment
adjacency = [[False]*n for _ in range(n)]
for i in range(n):
    for j in range(i+1, n):
        # check if responses i and j are semantically equivalent
        if are_semantically_equivalent(
               responses[i], responses[j], 
               question, 
               tokenizer, 
               model, 
               device=device
           ):
            adjacency[i][j] = True
            adjacency[j][i] = True
            
# Then BFS cluster, same logic as before
visited = [False]*n
clusters = []
for i in range(n):
    if not visited[i]:
        stack = [i]
        visited[i] = True
        cluster_members = []
        while stack:
            node = stack.pop()
            cluster_members.append(node)
            for nb in range(n):
                if adjacency[node][nb] and not visited[nb]:
                    visited[nb] = True
                    stack.append(nb)
        clusters.append(cluster_members)
# print the clusters
for c in clusters:
    print(c) # this should be the clusters of the responses
    # i also want to print the responses in the cluster
    for idx in c:
        print(responses[idx])
    
# Then compute the cluster-level grounding and entropy 
# total_entropy = 0.0
# for c in clusters:
#     cluster_size = len(c)
#     yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
#     p = yes_count / cluster_size

#     if p == 0 or p == 1:
#         h_cluster = 0.0
#     else:
#         h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

#     weight = cluster_size / n
#     total_entropy += weight * h_cluster
# total_grounding_entropy = 0.0 
grounding_score_with_entropy = 0.0
for c in clusters:
    cluster_size = len(c)
    yes_count = sum(1 for idx in c if groundings[idx].lower() == "yes")
    p = yes_count / cluster_size

    if p == 0 or p == 1:
        h_cluster = 0.0
    else:
        h_cluster = - (p * math.log2(p) + (1 - p)*math.log2(1 - p))

    # lets take the grounding score of the cluster, no of yes in the cluster / total no of responses in the cluster
    no_of_yes_in_cluster = sum(1 for idx in c if groundings[idx].lower() == "yes")
    cluster_size = len(c)
    grounding_score = no_of_yes_in_cluster / cluster_size
    grounding_score_with_entropy = grounding_score * h_cluster
    
# print('Entropy:', total_entropy)
print('Grounding Score:', grounding_score)

[0, 17, 16, 13, 12, 9, 8, 5, 4, 1]
yes the capital of france is paris
paris is the capital of france
yes the capital of france is paris
paris is the capital of france
yes the capital of france is paris
paris is the capital of france
yes the capital of france is paris
paris is the capital of france
yes the capital of france is paris
paris is the capital of france
[2, 19, 18, 15, 14, 11, 10, 7, 6, 3]
no the capital of france is not paris
no paris is not the capital of france
no the capital of france is not paris
no paris is not the capital of france
no the capital of france is not paris
no paris is not the capital of france
no the capital of france is not paris
no paris is not the capital of france
no the capital of france is not paris
no paris is not the capital of france
Grounding Score: 0.0

In [17]:
responses

['yes the capital of france is paris',
 'paris is the capital of france',
 'no the capital of france is not paris',
 'no paris is not the capital of france',
 'yes the capital of france is paris',
 'paris is the capital of france',
 'no the capital of france is not paris',
 'no paris is not the capital of france',
 'yes the capital of france is paris',
 'paris is the capital of france',
 'no the capital of france is not paris',
 'no paris is not the capital of france',
 'yes the capital of france is paris',
 'paris is the capital of france',
 'no the capital of france is not paris',
 'no paris is not the capital of france',
 'yes the capital of france is paris',
 'paris is the capital of france',
 'no the capital of france is not paris',
 'no paris is not the capital of france']

In [18]:
# df['entropy_grounding_llama32_70b_processed'].value_counts()

In [19]:
# save the dataframe
df.to_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed_with_grounding_entropy.csv', index=False)

In [14]:
import pandas as pd

df_internal = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed_internal_g_entropy.csv')

df_external = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed_external_g_entropy.csv')

In [3]:
df_internal['grounding_llama32V_with_cluster_wise_entropy'].value_counts()

grounding_llama32V_with_cluster_wise_entropy
0.000000    1157
0.027778      26
0.029412      24
0.031250      22
0.038462      15
            ...
0.076525       1
0.053699       1
0.059225       1
0.138557       1
0.023546       1
Name: count, Length: 192, dtype: int64

In [15]:
df_external['grounding_llama32V_with_external_entropy'].value_counts()

grounding_llama32V_with_external_entropy
0.306099    366
0.290794    232
0.275489    149
0.244879     76
0.260184     74
0.321404     64
0.214269     63
0.321404     56
0.183659     51
0.229574     49
0.168354     48
0.153049     46
0.198964     46
0.137744     34
0.336708     26
0.107135     26
0.122439     24
0.076525     24
0.306099     23
0.091830     21
0.275489     20
0.290794     15
0.336708     13
0.061220     11
0.352013     11
0.260184      8
0.030610      6
0.352013      5
0.045915      5
0.367318      4
0.367318      4
0.321404      4
0.336708      3
0.015305      2
0.382623      2
0.352013      2
0.306099      1
0.382623      1
0.443843      1
0.352013      1
0.413233      1
0.397928      1
0.000000      1
0.474453      1
0.367318      1
Name: count, dtype: int64

#### Debug of the grounding model entropy external

In [7]:
def calc_external_grounding_uncertainty(row):
    """
    Computes uncertainty score based on multiple grounding models.
    """

    try:
        modelA = ast.literal_eval(row["grounding_llama32_11b_processed_score"])
        modelB = ast.literal_eval(row["grounding_llama32_70b_processed_score"])
        modelC = ast.literal_eval(row["grounding_qwen_vl_processed_score"])
    except:
        modelA = row["grounding_llama32_11b_processed_score"]
        modelB = row["grounding_llama32_70b_processed_score"]
        modelC = row["grounding_qwen_vl_processed_score"]

    if not isinstance(modelA, list) or not isinstance(modelB, list) or not isinstance(modelC, list):
        return 0.0  # Ensure inputs are lists

    num_responses = min(len(modelA), len(modelB), len(modelC))

    if num_responses == 0:
        return 0.0  # No responses

    total_score = 0.0
    for i in range(num_responses):
        answers = [
            str(modelA[i]).lower().strip(),
            str(modelB[i]).lower().strip(),
            str(modelC[i]).lower().strip()
        ]
        yes_count = sum(ans == "yes" for ans in answers)
        p = yes_count / 3.0

        H = 0.0 if p in [0, 1] else - (p * math.log2(p) + (1 - p) * math.log2(1 - p))
        resp_score = H * p
        total_score += resp_score

    return total_score / num_responses

In [8]:
df = pd.read_csv('/staging/users/tpadhi1/Multimodal-Uncertainty-Quantification/my_outputs/merged_with_grounding_processed.csv')

In [9]:
df.columns

Index(['question_id', 'accuracy', 'predictive_entropy', 'lexical_similarity',
       'semantic_entropy', 'num_clusters', 'responses', 'resp_log_probs',
       'question', 'grounding_biomedclip', 'grounding_biomedclip_processed',
       'grounding_llama32_11b', 'grounding_llama32_11b_processed',
       'grounding_llama32_70b', 'grounding_llama32_70b_processed',
       'grounding_qwen_vl', 'grounding_qwen_vl_processed',
       'max_grounding_biomedclip', 'predictive_entropy_min_max_scaled',
       'lexical_similarity_min_max_scaled', 'semantic_entropy_min_max_scaled',
       'num_clusters_min_max_scaled', 'grounding_biomedclip_processed_scaled',
       'grounding_biomedclip_processed_scaled_average',
       'grounding_llama32_11b_processed_score',
       'grounding_llama32_70b_processed_score',
       'grounding_qwen_vl_processed_score',
       'grounding_llama32_11b_llama32_70b_agreement',
       'grounding_llama32_11b_qwen_vl_agreement',
       'grounding_llama32_70b_qwen_vl_agreement',
       'grounding_models_entropy_llama11b_llama70b_qwenvl',
       'grounding_models_entropy_llama11b_llama70b',
       'grounding_models_entropy_llama11b_qwenvl',
       'grounding_models_entropy_llama70b_qwenvl'],
      dtype='object')

In [ ]:
df['grounding_llama32_11b_processed_score']